warnings_are_errors: false

language: r

cache: packages

sudo: false

r:
  - bioc-devel
  - bioc-release

bioc_packages:
  - BiocStyle
  - testthat
  - DESeq2
  - limma
  - scater

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'

